# -*- coding: utf-8 -*-
"""EuroHealth_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNnfGznTOYaM5IV7ToFA6du9O3lC_6xu
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from google.cloud import bigquery
from google.oauth2 import service_account

project_id = 'product-analytics-494706'
dataset = 'dbt_health_app'

st.set_page_config(page_title='EuroHealth Product Dashboard',layout='wide')

gcp_credentials = {
    "type": st.secrets["gcp_service_account"]["type"],
    "project_id": st.secrets["gcp_service_account"]["project_id"],
    "private_key_id": st.secrets["gcp_service_account"]["private_key_id"],
    "private_key": st.secrets["gcp_service_account"]["private_key"].replace('\\n','\n'),
    "client_email": st.secrets["gcp_service_account"]["client_email"],
    "client_id": st.secrets["gcp_service_account"]["client_id"],
    "auth_uri": st.secrets["gcp_service_account"]["auth_uri"],
    "token_uri": st.secrets["gcp_service_account"]["token_uri"],
    "auth_provider_x509_cert_url": st.secrets["gcp_service_account"]["auth_provider_x509_cert_url"],
    "client_x509_cert_url": st.secrets["gcp_service_account"]["client_x509_cert_url"],
}

credentials = credentials = service_account.Credentials.from_service_account_info(gcp_credentials)
client = bigquery.Client(credentials=credentials, project=project_id)

@st.cache_data
def load_dau_data():
  query= f"""
    SELECT
      DATE(session_start_at) AS activity_date,
      COUNT(DISTINCT user_id) AS daily_active_users
    FROM `{project_id}.{dataset}.fct_user_activity`
    GROUP BY
      activity_date
    ORDER BY
      activity_date ASC
  """
  return client.query(query).to_dataframe()

@st.cache_data
def load_funnel_data():
  query = f"""
    WITH session_events AS (
      SELECT
        session_id,
        COUNT(CASE WHEN event_type= 'login' THEN 1 END) AS logged_in,
        COUNT(CASE WHEN event_type = 'view_dashboard' THEN 1 END) AS viewed_dashboard,
        COUNT(CASE WHEN event_type = 'click_upload' THEN 1 END) AS clicked_upload
      FROM `{project_id}.{dataset}.stg_events`
      GROUP BY
        session_id
    )
    SELECT
      '1. Logins' AS funnel_step,
      COUNT(DISTINCT CASE WHEN logged_in > 0 THEN session_id END) AS user_count
    FROM session_events
    UNION ALL
    SELECT
      '2. Dashboard Views' AS funnel_step,
      COUNT(DISTINCT CASE WHEN viewed_dashboard > 0 THEN session_id END) AS user_count
    FROM session_events
    UNION ALL
    SELECT
      '3. Upload Clicks' AS funnel_step,
      COUNT(DISTINCT CASE WHEN clicked_upload > 0 THEN session_id END) AS user_count
    FROM session_events
    ORDER BY
      funnel_step ASC
  """
  return client.query(query).to_dataframe()


# Dashboard UI
st.title('📊 EuroHealth App - Product Analytics')
st.markdown('Welcome to the Product Analytics Dashboard. Use the charts below to monitor user engagement and conversion metrics.')

st.divider() # Adds a horizontal line for visual separation

# Section 1: Daily Active Users (DAU)
st.header('Daily Active Users (DAU)')
with st.spinner('Loading DAU data...'):
  df_dau = load_dau_data()

  if not df_dau.empty:
    st.line_chart(
        data=df_dau.set_index('activity_date'),
        y='daily_active_users',
        width='stretch'
    )
  else:
    st.warning('No data found for Daily Active Users.')

st.divider()

# Section 2: Core Product Funnel
st.header('Core Funnel: Login to Upload')
st.markdown('This funnel tracks the volume of sessions moving from initial login to clicking the upload document buttion.')

with st.spinner('Loading Funnel data...'):
  df_funnel = load_funnel_data()

  if not df_funnel.empty:
    col1,col2 = st.columns([1,2])

    with col1:
      st.dataframe(df_funnel, hide_index=True)

      # Calculate and display the overall conversion rate
      initial_users = df_funnel.iloc[0]['user_count']
      final_users = df_funnel.iloc[-1]['user_count']
      if initial_users > 0:
        conversion_rate = (final_users / initial_users) * 100
        st.metric(label='Overall Conversion Rate',value=f'{conversion_rate:.1f}%')

    with col2:
      fig_bar = px.bar(
          df_funnel,
          x='funnel_step',
          y='user_count',
          width='stretch',
          title='Activity by Category',
          labels={'user_count':'Number of users','funnel_step':'Funnel Step'}
      )
      fig_bar.update_layout(xaxis_tickangle=90)
      st.plotly_chart(fig_bar,use_container_width=True)
        
  else:
    st.warning('No data found for the Product Funnel.')
      
st.sidebar.success('Dashboard successfully connected to BigQuery!')
